"""Adds validations

Revision ID: 034cd4f4d9f7
Revises: 53fc8fbb1b1a
Create Date: 2024-04-18 14:11:22.638029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034cd4f4d9f7'
down_revision = '53fc8fbb1b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(length=20), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
