"""Adds status column

Revision ID: 794b20ba9dc5
Revises: 838276b48bae
Create Date: 2024-04-18 14:58:22.394884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794b20ba9dc5'
down_revision = '838276b48bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
