"""Adding friendship model

Revision ID: 838276b48bae
Revises: 034cd4f4d9f7
Create Date: 2024-04-18 14:38:34.912202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838276b48bae'
down_revision = '034cd4f4d9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.alter_column('user_id1',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id2',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('user_id2',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id1',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
